"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

sum = 0
all = [1, 2]
number = 0
count = 0

while number < 4000000:
    number = all[count] + all[count+1]
    if number < 4000000:
        all.append(number)
    count +=1

for i in all:
    if i % 2 == 0:
        sum +=i
print(sum)